### ISSUE TITLE
Support for IPv6 only

### ISSUE THREAD

**Issue by mas-ugi** [mitcdh/ui-driver-scaleway#6]
Hi, 
How do I disable ipv4 allocation and use ipv6 only?
Since scaleway support ipv6 and my rancher server is in scaleway too.
it would be nice if I can do that, so i could roll some test with short lived hosts with quite cheap price.

Thank you.

**Comment by mitcdh** [comment]
This is just an interface for the [scaleway docker machine driver](https://github.com/scaleway/docker-machine-driver-scaleway). At the time I put this together the docker machine driver did not support only ipv6, at a glance that seems to still be the case.

Happy to implement the interface to do this if I'm mistaken or scaleway updates the machine driver.

**Comment by mas-ugi** [comment]
Sorry, I am not digging into this repo yet.
![image](https://user-images.githubusercontent.com/34763796/34472612-b946c08e-efa0-11e7-962a-1d28fd69e480.png)
In the machine driver the ip option is optional, in my understanding, that should not reserve ip if leaved empty. Yesterday i rolled up a host with empty ip and this still reserve an ipv4 address

![image](https://user-images.githubusercontent.com/34763796/34472645-6720d640-efa1-11e7-9d15-28b9c51b35b8.png)
On latest changelog they mention ipv6 option.

I can delete ipv4 reservation manually, but how about rancher, does it really support ipv6? that's still in my head

I will dig to this repo when available.

**Comment by mitcdh** [comment]
The option is there so that you can specify an existing IPv4 address in your scaleway account and the host will be provisioned with it. If you leave the field blank a new IPv4 address is allocated automatically.

I don't believe Rancher itself supports IPv6 yet, just based on this issue: https://github.com/rancher/rancher/issues/1403

**Comment by mas-ugi** [comment]
Okay, thank you for your support.
